mqtt:
  serverURIs: tcp://mqtt-server:1883
  username: admin
  password: 123456789
  client:
    id: spring-${random.value}
  topic: topic/test
server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/mqtt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456